---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: timmo001/workflows/.github/workflows/lint-general.yml@43e7be6974bb98454ffa56fc5a4b46cc160e09bc # master
