---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: timmo001/workflows/.github/workflows/lint-general.yml@010ccf64e49d2984bb5f0982d6ae7314114472a6 # master
