---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@bf115c44ad80cb1fe094a44a6359a6f12c7ab69b # master
    permissions:
      pull-requests: write
      contents: write
